version: '3.8'

services:
  node_app:
    build: .
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node_app

